# Uncomment this line to define a global platform for your project
inhibit_all_warnings!
platform :ios, '7.0'

target 'TBNetworking' do

pod 'AFNetworking', '2.6.3'

end

target 'TBNetworkingTests' do
pod 'OCMock', '~> 3.1.2'
pod 'OHHTTPStubs'
pod 'Nocilla'
pod 'Kiwi', '~> 2.4.0'
end


