# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'TBNetworking' do

pod 'AFNetworking'

end

target 'TBNetworkingTests' do
pod 'OCMock', '~> 3.1.2'
pod 'OHHTTPStubs'
pod 'Nocilla'
pod 'Kiwi', '~> 2.4.0'
end


